<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYMINW1588" ignored="14" name="MainFunctionsTest" tests="44" failures="6" timestamp="05 Jun 2017 13:20:04 GMT" time="0.011" errors="0">
  <testcase name="testSum" time="0.0" classname="testng.calculator.SumLongTest"/>
  <testcase name="testSum" time="0.0" classname="testng.calculator.SumLongTest"/>
  <testcase name="testSum" time="0.001" classname="testng.calculator.SumLongTest"/>
  <testcase name="testSum" time="0.0" classname="testng.calculator.SumLongTest"/>
  <testcase name="testSum" time="0.0" classname="testng.calculator.SumLongTest"/>
  <testcase name="testSum" time="0.0" classname="testng.calculator.SumLongTest"/>
  <testcase name="testSumDouble" time="0.0" classname="testng.calculator.SumDoubleTest"/>
  <testcase name="testSumDouble" time="0.0" classname="testng.calculator.SumDoubleTest"/>
  <testcase name="testSumDouble" time="0.0" classname="testng.calculator.SumDoubleTest"/>
  <testcase name="testSumDouble" time="0.0" classname="testng.calculator.SumDoubleTest"/>
  <testcase name="testSumDouble" time="0.0" classname="testng.calculator.SumDoubleTest">
    <failure type="java.lang.AssertionError" message="expected [2.5555] but found [2.5555000000000003]">
      <![CDATA[java.lang.AssertionError: expected [2.5555] but found [2.5555000000000003]
	at testng.calculator.SumDoubleTest.testSumDouble(SumDoubleTest.java:15)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testSumDouble -->
  <testcase name="testSumDouble" time="0.0" classname="testng.calculator.SumDoubleTest"/>
  <testcase name="testSubLong" time="0.0" classname="testng.calculator.SubLongTest"/>
  <testcase name="testSubLong" time="0.0" classname="testng.calculator.SubLongTest"/>
  <testcase name="testSubLong" time="0.0" classname="testng.calculator.SubLongTest"/>
  <testcase name="testSubLong" time="0.0" classname="testng.calculator.SubLongTest"/>
  <testcase name="testSubLong" time="0.0" classname="testng.calculator.SubLongTest"/>
  <testcase name="testSubDouble" time="0.0" classname="testng.calculator.SubDoubleTest"/>
  <testcase name="testSubDouble" time="0.0" classname="testng.calculator.SubDoubleTest"/>
  <testcase name="testSubDouble" time="0.0" classname="testng.calculator.SubDoubleTest"/>
  <testcase name="testSubDouble" time="0.0" classname="testng.calculator.SubDoubleTest"/>
  <testcase name="testSubDouble" time="0.0" classname="testng.calculator.SubDoubleTest">
    <failure type="java.lang.AssertionError" message="expected [0.5555] but found [0.5555000000000001]">
      <![CDATA[java.lang.AssertionError: expected [0.5555] but found [0.5555000000000001]
	at testng.calculator.SubDoubleTest.testSubDouble(SubDoubleTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testSubDouble -->
  <testcase name="testSubDouble" time="0.0" classname="testng.calculator.SubDoubleTest"/>
  <testcase name="testDivDouble" time="0.0" classname="testng.calculator.DivDoubleTest"/>
  <testcase name="testDivDouble" time="0.0" classname="testng.calculator.DivDoubleTest"/>
  <testcase name="testDivDouble" time="0.001" classname="testng.calculator.DivDoubleTest"/>
  <testcase name="testDivDouble" time="0.0" classname="testng.calculator.DivDoubleTest"/>
  <testcase name="divByZero" time="0.001" classname="testng.calculator.DivLongTest"/>
  <testcase name="testDivLong" time="0.0" classname="testng.calculator.DivLongTest"/>
  <testcase name="testDivLong" time="0.0" classname="testng.calculator.DivLongTest"/>
  <testcase name="testDivLong" time="0.0" classname="testng.calculator.DivLongTest"/>
  <testcase name="testDivLong" time="0.0" classname="testng.calculator.DivLongTest"/>
  <testcase name="testMultDouble" time="0.0" classname="testng.calculator.MultDoubleTest"/>
  <testcase name="testMultDouble" time="0.0" classname="testng.calculator.MultDoubleTest"/>
  <testcase name="testMultDouble" time="0.0" classname="testng.calculator.MultDoubleTest">
    <failure type="java.lang.AssertionError" message="expected [1.21] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.21] but found [1.0]
	at testng.calculator.MultDoubleTest.testMultDouble(MultDoubleTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testMultDouble -->
  <testcase name="testMultDouble" time="0.0" classname="testng.calculator.MultDoubleTest">
    <failure type="java.lang.AssertionError" message="expected [-2.31] but found [-3.0]">
      <![CDATA[java.lang.AssertionError: expected [-2.31] but found [-3.0]
	at testng.calculator.MultDoubleTest.testMultDouble(MultDoubleTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testMultDouble -->
  <testcase name="testMultDouble" time="0.0" classname="testng.calculator.MultDoubleTest">
    <failure type="java.lang.AssertionError" message="expected [1.555] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.555] but found [1.0]
	at testng.calculator.MultDoubleTest.testMultDouble(MultDoubleTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testMultDouble -->
  <testcase name="testMultDouble" time="0.0" classname="testng.calculator.MultDoubleTest"/>
  <testcase name="testMultLong" time="0.0" classname="testng.calculator.MultLongTest"/>
  <testcase name="testMultLong" time="0.0" classname="testng.calculator.MultLongTest"/>
  <testcase name="testMultLong" time="0.0" classname="testng.calculator.MultLongTest"/>
  <testcase name="testMultLong" time="0.0" classname="testng.calculator.MultLongTest"/>
  <testcase name="testMultLong" time="0.0" classname="testng.calculator.MultLongTest"/>
  <testcase name="divByZero" time="0.0" classname="testng.calculator.DivDoubleTest">
    <failure type="org.testng.TestException" message="
Method DivDoubleTest.divByZero()[pri:1, instance:testng.calculator.DivDoubleTest@5479e3f] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method DivDoubleTest.divByZero()[pri:1, instance:testng.calculator.DivDoubleTest@5479e3f] should have thrown an exception of type class java.lang.NumberFormatException
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- divByZero -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
</testsuite> <!-- MainFunctionsTest -->
