<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYMINW1588" ignored="8" name="TrigonometryTest" tests="18" failures="9" timestamp="05 Jun 2017 13:20:04 GMT" time="0.024" errors="0">
  <testcase name="testCos" time="0.002" classname="testng.calculator.CosTest">
    <failure type="java.lang.AssertionError" message="expected [1.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [1.0] but found [0.0]
	at testng.calculator.CosTest.testCos(CosTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testCos" time="0.0" classname="testng.calculator.CosTest">
    <failure type="java.lang.AssertionError" message="expected [0.866] but found [0.5]">
      <![CDATA[java.lang.AssertionError: expected [0.866] but found [0.5]
	at testng.calculator.CosTest.testCos(CosTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testCos" time="0.0" classname="testng.calculator.CosTest"/>
  <testcase name="testCos" time="0.0" classname="testng.calculator.CosTest">
    <failure type="java.lang.AssertionError" message="expected [0.5] but found [0.866]">
      <![CDATA[java.lang.AssertionError: expected [0.5] but found [0.866]
	at testng.calculator.CosTest.testCos(CosTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testCos" time="0.0" classname="testng.calculator.CosTest">
    <failure type="java.lang.AssertionError" message="expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [0.0] but found [1.0]
	at testng.calculator.CosTest.testCos(CosTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCos -->
  <testcase name="testSin" time="0.0" classname="testng.calculator.SinTest"/>
  <testcase name="testSin" time="0.0" classname="testng.calculator.SinTest"/>
  <testcase name="testSin" time="0.0" classname="testng.calculator.SinTest"/>
  <testcase name="testSin" time="0.0" classname="testng.calculator.SinTest"/>
  <testcase name="testSin" time="0.0" classname="testng.calculator.SinTest"/>
  <testcase name="testTg" time="0.001" classname="testng.calculator.TgTest">
    <failure type="java.lang.AssertionError" message="expected [0.577] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [0.577] but found [1.0]
	at testng.calculator.TgTest.testTg(TgTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testTg -->
  <testcase name="testTg" time="0.0" classname="testng.calculator.TgTest"/>
  <testcase name="testTg" time="0.0" classname="testng.calculator.TgTest"/>
  <testcase name="testTg" time="0.0" classname="testng.calculator.TgTest">
    <failure type="java.lang.AssertionError" message="expected [1.732] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.732] but found [1.0]
	at testng.calculator.TgTest.testTg(TgTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testTg -->
  <testcase name="testCtg" time="0.001" classname="testng.calculator.CtgTest">
    <failure type="java.lang.AssertionError" message="expected [1.732] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [1.732] but found [1.0]
	at testng.calculator.CtgTest.testCtg(CtgTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testCtg" time="0.0" classname="testng.calculator.CtgTest"/>
  <testcase name="testCtg" time="0.0" classname="testng.calculator.CtgTest">
    <failure type="java.lang.AssertionError" message="expected [0.577] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [0.577] but found [1.0]
	at testng.calculator.CtgTest.testCtg(CtgTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="testCtg" time="0.0" classname="testng.calculator.CtgTest">
    <failure type="java.lang.AssertionError" message="expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: expected [0.0] but found [1.0]
	at testng.calculator.CtgTest.testCtg(CtgTest.java:14)
	at testng.runner.TestRunner.main(TestRunner.java:33)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCtg -->
  <testcase name="ctg0" time="0.0" classname="testng.calculator.CtgTest">
    <ignored/>
  </testcase> <!-- ctg0 -->
  <testcase name="tg90" time="0.0" classname="testng.calculator.TgTest">
    <ignored/>
  </testcase> <!-- tg90 -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@BeforeSuite setPhrase" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setPhrase -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
  <testcase name="@AfterSuite setPhraseDone" time="0.0" classname="testng.calculator.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite setPhraseDone -->
</testsuite> <!-- TrigonometryTest -->
